language: python
sudo: false
cache:
  directories:
  - $HOME/virtualenv
python:
- 2.7
install:
- pip install -r requirements.pip
- pip install -r requirements-dev.pip
- pip install coveralls
script:
- nosetests --with-coverage --cover-tests --cover-html --cover-package=uws
after_success:
- coveralls
